### ISSUE TITLE
Class "App\Facades\SiteSettings" not found

### ISSUE THREAD

**Issue by eliysha** [liberusoftware/boilerplate-laravel#221]
### Details

From a fresh install, I'm getting this error on login page : `Class "App\Facades\SiteSettings" not found`
<img width="1368" alt="image" src="https://github.com/user-attachments/assets/28778adf-1449-4b26-8b87-c37c571752fa">

I run composer-install ✅ 
<img width="866" alt="image" src="https://github.com/user-attachments/assets/188369bf-9a2b-4523-812c-a485a4f6c4a8">

How to fix please ?

Mac OS x Sonoma
MAMP PRO : PHP 8.3.9

**Comment by Raza9798** [comment]
remove `App\Facades\SiteSettings` install the following package to manage the SiteSettings effectively https://packagist.org/packages/intelrx/sitesettings

**Comment by eliysha** [comment]
So the app isn't working out the box.
I followed set up instructions.
Then I added the package mentioned above (not present in the Readme)
Now I'm getting another error

<img width="1387" alt="image" src="https://github.com/user-attachments/assets/6f67e03a-ee91-4d6a-b712-a27c2cfe8421">

Please is it possible to have all instructions to setup the app ?

Thank you
